version: '2'
services:
  feed_writer:
    environment:
      - PORT
    build: ../feed_writer
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - feed_reader
  feed_reader:
    build: ../feed_reader
