version: '2'
services:
  feed-writer:
    environment:
      - PORT
      - HOSTNAME=feed-reader
    image: gcr.io/${PROJECT_ID}/feed-writer:latest
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - feed-reader
  feed-reader:
    image: gcr.io/${PROJECT_ID}/feed-reader:latest
    ports:
      - "81:81"
