version: '2'
services:
  feed-writer:
    build: ../feed_writer
    image: gcr.io/${PROJECT_ID}/feed-writer:latest
  feed-reader:
    build: ../feed_reader
    image: gcr.io/${PROJECT_ID}/feed-reader:latest
