version: '2'
services:
  feed_writer:
    environment:
      - PORT
    image: gcr.io/${PROJECT_ID}/feed-writer:v1
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - feed_reader
  feed_reader:
    image: gcr.io/${PROJECT_ID}/feed-reader:v2
